export const notes = [
    "c-2", "c-sharp-2", "d-2", "d-sharp-2", "e-2", "f-2", "f-sharp-2", "g-2", "g-sharp-2", "a-3", "a-sharp-3", "b-3",
    "c-3", "c-sharp-3", "d-3", "d-sharp-3", "e-3", "f-3", "f-sharp-3", "g-3", "g-sharp-3", "a-4", "a-sharp-4", "b-4",
    "c-4", "c-sharp-4", "d-4", "d-sharp-4", "e-4", "f-4", "f-sharp-4", "g-4", "g-sharp-4", "a-5", "a-sharp-5", "b-5",
    "c-5", "c-sharp-5", "d-5", "d-sharp-5", "e-5",
];

export const keybindings = {
    "`": "c-2",
    "1": "c-sharp-2",
    "q": "d-2",
    "2": "d-sharp-2",
    "3": "e-2",
    "4": "f-2",
    "r": "f-sharp-2",
    "5": "g-2",
    "6": "g-sharp-2",
    "7": "a-3",
    "8": "a-sharp-3",
    "i": "b-3",
    "a": "c-3",
    "w": "c-sharp-3",
    "s": "d-3",
    "e": "d-sharp-3",
    "d": "e-3",
    "f": "f-3",
    "t": "f-sharp-3",
    "g": "g-3",
    "y": "g-sharp-3",
    "h": "a-4",
    "u": "a-sharp-4",
    "j": "b-4",
    "k": "c-4",
    "o": "c-sharp-4",
    "l": "d-4",
    "p": "d-sharp-4",
    ";": "e-4",
    "z": "f-4",
    "x": "f-sharp-4",
    "c": "g-4",
    "v": "g-sharp-4",
    "b": "a-5",
    "n": "a-sharp-5",
    "m": "b-5"
    
}
